mysql:
  username: root
  password: 123456
  address: 127.0.0.1
  port: 3306
  database: imdb
  charset: utf8mb4
  parseTime: True
  loc: Local
redis:
  addr: 172.30.255.250
  port: 6379
  password: 
  db: 0
  poolsize: 30
  minIdleSize: 30